# Generated by Django 4.2.4 on 2023-08-21 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Payer Group',
                'verbose_name_plural': '1. Payer Groups',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.IntegerField(blank=True, null=True, unique=True)),
                ('vendor_id', models.IntegerField(blank=True, null=True)),
                ('payer_name', models.CharField(max_length=100)),
                ('clerk', models.CharField(choices=[('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27')], max_length=100)),
                ('channel', models.CharField(choices=[('ON-TRADE', 'On Trade'), ('OFF-TRADE', 'Off Trade')], max_length=100)),
                ('collector', models.CharField(choices=[('Sabina Lang', 'Sabina Lang'), ('Aleta Alekbarova', 'Aleta Alekbarova'), ('Jan Kucirek', 'Jan Kucirek'), ('Hugo Milon', 'Hugo Milon'), ('Florian Zanon', 'Florian Zanon'), ('Thomas Fitting', 'Thomas Fitting'), ('Brice Picolet', 'Brice Picolet'), ('Gustavo Sanez', 'Gustavo Sanez')], max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_surname', models.CharField(blank=True, max_length=100)),
                ('contact_gender', models.CharField(blank=True, choices=[('WOMAN', 'Woman'), ('MAN', 'Man')], max_length=100)),
                ('phone_num', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=300)),
                ('edi', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, default='default_cust.jpg', null=True, upload_to='customer_pics')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country')),
                ('payer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.payergroup')),
            ],
            options={
                'verbose_name': 'Payer',
                'verbose_name_plural': '2. Payers',
            },
        ),
    ]
