# Generated by Django 4.2.4 on 2023-08-21 21:46

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': '2. Analysis',
            },
        ),
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unikey', models.CharField(max_length=300)),
                ('payer', models.IntegerField()),
                ('assignment', models.CharField(max_length=200)),
                ('clerks', models.IntegerField()),
                ('type', models.CharField(max_length=2)),
                ('doc_date', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('text', models.CharField(blank=True, max_length=300, null=True)),
                ('clearing_doc', models.IntegerField(blank=True, null=True)),
                ('clearing_date', models.DateField(blank=True, null=True)),
                ('reason_code', models.CharField(blank=True, max_length=3)),
                ('dunning_block', models.CharField(blank=True, max_length=3)),
                ('billing_doc', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Deduction',
                'verbose_name_plural': '1. Deductions',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': '5. Owners',
            },
        ),
        migrations.CreateModel(
            name='RootCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deduction.analysis')),
            ],
            options={
                'verbose_name': 'RootCause',
                'verbose_name_plural': '3. Rootcauses',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deduction.analysis')),
                ('rootcause', smart_selects.db_fields.ChainedForeignKey(chained_field='analysis', chained_model_field='analysis', on_delete=django.db.models.deletion.CASCADE, to='deduction.rootcause')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': '4. Actions',
            },
        ),
        migrations.CreateModel(
            name='CollectorsInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unikey', models.CharField(help_text='This is the unique identifier for the deduction.', max_length=300)),
                ('action_date', models.DateField(blank=True, null=True)),
                ('nb_com', models.CharField(blank=True, choices=[('1st Communication', '1st Communication'), ('Multiple communications', 'Multiple communications')], max_length=100)),
                ('proof_com', models.CharField(blank=True, max_length=50)),
                ('comment', models.TextField(blank=True, max_length=2000, null=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deduction.action')),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deduction.analysis')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deduction.owner')),
                ('rootcause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deduction.rootcause')),
            ],
            options={
                'verbose_name': 'Collector analysis',
                'verbose_name_plural': "6. Collector's analysis",
                'unique_together': {('unikey', 'analysis', 'rootcause', 'action')},
            },
        ),
    ]
