# Generated by Django 4.2.4 on 2023-08-21 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Closed', 'Closed'), ('Open', 'Open')], default='Open', max_length=50)),
                ('collector', models.CharField(blank=True, choices=[('Sabina Lang', 'Sabina Lang'), ('Aleta Alekbarova', 'Aleta Alekbarova'), ('Jan Kucirek', 'Jan Kucirek'), ('Hugo Milon', 'Hugo Milon'), ('Florian Zanon', 'Florian Zanon'), ('Thomas Fitting', 'Thomas Fitting'), ('Brice Picolet', 'Brice Picolet'), ('Gustavo Sanez', 'Gustavo Sanez')], max_length=100, null=True)),
                ('payer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.payergroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
